require 'plugin-config.autopairs'
require 'plugin-config.comment'
require 'plugin-config.lsp'
require 'plugin-config.lualine'
require 'plugin-config.nvim-cmp'
require 'plugin-config.telescope'
require 'plugin-config.treesitter'
